apiVersion: batch/v1
kind: Job
metadata:
  name: rl-training
spec:
  parallelism: 1
  completions: 1
  backoffLimit: 6
  template:
    metadata:
      name: rl-training
    spec:
      restartPolicy: "OnFailure"
      containers:
      - name: ros
        image: axyz1288/aidocker:ros
        securityContext:
          runAsUser: 1000
        ports:
        - containerPort: 11311

      - name: pybullet
        image: axyz1288/aidocker:pybullet
        securityContext:
          runAsUser: 1000
        ports:
        - containerPort: 11311
        resources:
          requests:
            memory: "10M"
            cpu: "0.1"
          limits:
            memory: "100M"
            cpu: "0.5"
        volumeMounts:
        - name: x11
          mountPath: /tmp/.X11-unix
        - name: pybullet
          mountPath: /home/aiRobots
        envFrom:
        - configMapRef:
            name: gui
        args: ["/bin/python3", "./AGV.py", "-E=agv", "-A=gacomm", "-m=./AGV.npy"]

      - name: pytorch
        image: axyz1288/aidocker:pytorch
        securityContext:
          runAsUser: 1000
        ports:
        - containerPort: 11311
        - containerPort: 6006
        resources:
          requests:
            memory: "4G"
            cpu: "1"
          limits:
            memory: "8G"
            cpu: "4"
        volumeMounts:
        - name: pytorch
          mountPath: /home/aiRobots
        args: ["/bin/python3", "./main.py", "-E=agv", "-A=gacomm", "--gpu=cuda:1"]

      volumes:
      - name: x11
        persistentVolumeClaim:
          claimName: x11
      - name: pybullet
        persistentVolumeClaim:
          claimName: pybullet
      - name: pytorch
        persistentVolumeClaim:
          claimName: pytorch