kind: Service
apiVersion: v1
metadata:
  name: tensorboard
  namespace: rl
spec:
  type: NodePort
  selector:
    app: rl
  ports:
  - protocol: TCP
    port: 6006
    targetPort: 6006
    nodePort: 32480