apiVersion: v1
kind: PersistentVolume
metadata:
  name: pybullet
spec:
  storageClassName: local-storage
  local:
    path: /home/airobots/MARL/env
  capacity:
    storage: 10Mi
  volumeMode: Filesystem
  accessModes: [ReadWriteMany]
  persistentVolumeReclaimPolicy: Retain
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions: 
        - key: beta.kubernetes.io/os
          operator: In
          values: [linux]
  
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pybullet
spec:
  storageClassName: local-storage
  accessModes: [ReadWriteMany]
  resources:
    requests:
      storage: 10Mi

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pytorch
spec:
  storageClassName: local-storage
  local:
    path: /home/airobots/MARL
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes: [ReadWriteMany]
  persistentVolumeReclaimPolicy: Retain
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions: 
        - key: beta.kubernetes.io/os
          operator: In
          values: [linux]
  
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pytorch
spec:
  storageClassName: local-storage
  accessModes: [ReadWriteMany]
  resources:
    requests:
      storage: 10Gi