apiVersion: v1
kind: PersistentVolume
metadata:
  name: x11
spec:
  storageClassName: local-storage
  local:
    path: /tmp/.X11-unix
  capacity:
    storage: 1Mi
  volumeMode: Filesystem
  accessModes: [ReadWriteMany]
  persistentVolumeReclaimPolicy: Retain
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions: 
        - key: kubernetes.io/arch
          operator: In
          values: ["amd64"]
  
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: x11
spec:
  storageClassName: local-storage
  accessModes: [ReadWriteMany]
  resources:
    requests:
      storage: 1Mi